<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Facebook helps you connect and share with the people in your life__6lux</name>
   <tag></tag>
   <elementGuidId>3c9d6aec-d73b-4e04-91ae-1e307eec5bb0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='u_0_2_Wi']/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div._6lux</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>880e818d-41e3-43ee-ac90-8b1fac3262e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_6lux</value>
      <webElementGuid>24fa7016-5036-457d-8592-1bc58d6c12e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;u_0_2_Wi&quot;)/div[1]/div[@class=&quot;_6lux&quot;]</value>
      <webElementGuid>b4ca0c4b-2791-43e2-904c-f4011e60e280</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='u_0_2_Wi']/div/div</value>
      <webElementGuid>8aa674e7-c845-45c4-b7e8-29e387432d74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div</value>
      <webElementGuid>a3bf3714-914b-4ee6-91ec-4a5ff099dedd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
